### ISSUE TITLE
gestire latenza http e caricamenti vari

### ISSUE THREAD

**Issue by bianchimro** [qandobooking/ionic-dashboard#9]
controllare su tutte le viste.

**Comment by gffuma** [comment]
I caricamenti iniziali sono a posto, vanno gestiti i caricamenti e gli errori sulle post per intenderci, per i caricamenti basta uno ionic loader che va tirato su/giù esplicitamente nei controller per gli errori una cosa simile che fa vedere una notifica che sparisce.

**Comment by bianchimro** [comment]
chiudiamo questa,le notifiche/errori sono gestite da #26
